[2023-11-19 16:32:13,005] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.20s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.37s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.49s/it]

  0%|          | 0/4 [00:00<?, ?it/s]
  0%|          | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/sailhome/jphilipp/research_projects/printllama/experiments/apps/add_codellama_prints.py", line 82, in <module>
    main()
  File "/sailhome/jphilipp/research_projects/printllama/experiments/apps/add_codellama_prints.py", line 79, in main
    add_codellama_prints(args, codellama)
  File "/sailhome/jphilipp/research_projects/printllama/experiments/apps/add_codellama_prints.py", line 45, in add_codellama_prints
    item['codellama_print_statements'] = generate_print_statements(question, faulty_solution, codellama, args.n_prints)
  File "/sailhome/jphilipp/research_projects/printllama/experiments/apps/add_codellama_prints.py", line 27, in generate_print_statements
    codellama_print = codellama(prompt)
  File "/sailhome/jphilipp/research_projects/printllama/experiments/apps/add_codellama_prints.py", line 27, in generate_print_statements
    codellama_print = codellama(prompt)
  File "/scr/jphilipp/miniconda3/envs/printllama/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/scr/jphilipp/miniconda3/envs/printllama/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
[2023-11-19 16:32:23,251] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1920427) of binary: /scr/jphilipp/miniconda3/envs/printllama/bin/python
Traceback (most recent call last):
  File "/scr/jphilipp/miniconda3/envs/printllama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/scr/jphilipp/miniconda3/envs/printllama/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/scr/jphilipp/miniconda3/envs/printllama/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/scr/jphilipp/miniconda3/envs/printllama/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/scr/jphilipp/miniconda3/envs/printllama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/scr/jphilipp/miniconda3/envs/printllama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
add_codellama_prints.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-19_16:32:23
  host      : cocoflops-hgx-1.stanford.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1920427)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
